{% set version = "0.7" %}
{% set build_number = "0" %}
{% set sha_hash = "13f60672b324d081545f423d720737121c4952a9b90bdd49dc372a84c3fe96ee" %}

package:
  name: dlpack
  version: {{ version }}

source:
  url: https://github.com/dmlc/dlpack/archive/v{{ version }}.tar.gz
  sha256: {{ sha_hash }}

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base

test:
  commands:
    - test -f ${PREFIX}/include/dlpack/dlpack.h  # [unix]
    - test -f ${PREFIX}/bin/mock                 # [unix]

about:
  home: https://github.com/dmlc/dlpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DLPack - Open In Memory Tensor Structure
  description: |
    DLPack is an open in-memory tensor structure to for sharing tensor among frameworks
  dev_url: https://github.com/dmlc/dlpack

extra:
  recipe-maintainers:
    - marcelotrevisani
    - kkraus14
    - jakirkham
